title: Do it youself
theme: minima
author: Iwuji Anthony
email: anabizconcept9@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  we provide info on how you can actually install yourhome appliances yourself. These appliances include plasma Tv, air conditioner, 
  washing machine, gas cookers, refrigrators, dstv, gotv, startimes and even carry out some electrical installations.
# social links
twitter_username: Anabiz1
github_username:  Anabiz
show_excerpts: true # set to false to remove excerpts on the homepage
