title: infomation on electronic,electrical and cable Tv installation.
author: Iwuji Anthony
email: anabizconcept9@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  we offer information on how you can install home appliances like plasma tv, tv stand, ceilling fan, dstv, gotv, cable tv and electrical 
  installation maintanance.
# 
twitter_username: Anabiz1
github_username:  Anabiz
show_excerpts: true # set to false to remove excerpts on the homepage
